//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructorRequest
    {
        public int ConstructorRequestId { get; set; }
        public Nullable<int> ReqId { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> Qty { get; set; }
        public string Unit { get; set; }
        public string Date { get; set; }
        public string SiteStatus { get; set; }
        public string Immidiate { get; set; }
    }
}
