//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodReceipt
    {
        public int GoodReceiptId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public string PurchaseOrderReference { get; set; }
        public string OrderDetails { get; set; }
    }
}
