//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int PurchaseOrderId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderStatus { get; set; }
        public string OrderDate { get; set; }
        public string IsDraftPurchaseOrder { get; set; }
        public string OnHold { get; set; }
    }
}
