//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int SiteId { get; set; }
        public Nullable<int> SID { get; set; }
        public string SiteName { get; set; }
        public string Address { get; set; }
        public Nullable<double> StarageCapacity { get; set; }
        public Nullable<double> CurrentCapacity { get; set; }
    }
}
