//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SupplierId { get; set; }
        public Nullable<int> SupId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> BankAccountNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Availability { get; set; }
        public string Rate { get; set; }
    }
}
